### ISSUE TITLE
Передача данных в программу

### ISSUE THREAD

**Issue by AkshachRd** [tanyginvv/travelline_practice#15]
https://github.com/tanyginvv/travelline_practice/blob/ecf57c62bb54131f3f41214f38bdbe6803667033/homework(typescript)/src/1-tools.ts#L6-L21

У тебя для парсера отдаётся path и уже внутри программы получение контента.
Для json ты почему-то прям здесь получаешь контент, и уже его отдаёшь в программу.
Выбери один из способов и приведи к общему слагаемому обе программы.

**Comment by tanyginvv** [comment]
теперь в обоих случаях передаю путь
